# Workflow name
name: frontend-movie-picture-pipeline
# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main

jobs:
  pre-build:
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 'latest'
        - name: Install dependencies
          run: npm ci --silent
        - name: Lint code
          id: lint
          run: |
            echo "Linting..."
            npm run lint
        - name: Run tests
          run: npm test

#   build-actions:
#     needs: [pre-build]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Publish test results
        