name: build-and-test-backend-app

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  lint-code:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    defaults:
      run:
        shell: bash
        working-directory: starter/backend
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Setup pipenv
        run: pip install pipenv

      - name: Dependency Caching
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: python-3.10-${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Project Dependencies
        run: pipenv install --dev

      - name: Execute linting
        run: pipenv run lint

  test-code:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    defaults:
      run:
        shell: bash
        working-directory: starter/backend
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Setup pipenv
        run: pip install pipenv

      - name: Dependency Caching
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: python-3.10-${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Project Dependencies
        run: pipenv install --dev

      - name: Run tests
        run: pipenv run test

  build-docker-image:
    needs: [lint-code, test-code]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: starter/backend
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup pipenv
        run: pip install pipenv

      - name: Dependency Caching
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: python-dependencies-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Project Dependencies
        run: pipenv install --dev

      - name: Build Docker Image
        run: docker build --tag mp-backend:latest .

      - name: Deploy Docker Container
        run: docker run -p 5000:5000 --name mp-backend -d mp-backend

      - name: Verify Deployment
        run: curl http://localhost:5000/movies

      - name: Stop Docker Container
        run: docker stop mp-backend